apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tibia-secret
  namespace: apps
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: my-secret-store
    kind: ClusterSecretStore
  target:
    name: tibia
    creationPolicy: Owner
  data:
    - secretKey: tibia-mariadb-user
      remoteRef:
        key: mysql_user
    - secretKey: tibia-mariadb-password
      remoteRef:
        key: mysql_password
    - secretKey: tibia-mariadb-root-password
      remoteRef:
        key: mysql_root_password
    - secretKey: tibia-mariadb-database
      remoteRef:
        key: mysql_database
