apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-tls
  namespace: kube-system
spec:
  secretName: gatus-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - status.mythbound.dev
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
