apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
data:
  config.yaml: |
    metrics: true
    endpoints:
      - name: github
        url: https://api.github.com/healthz
        interval: 5m
        conditions:
          - "[STATUS] == 200"
