apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gatus-status
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`status.mythbound.dev`)
      kind: Rule
      services:
        - name: gatus
          port: 8080
  tls:
    secretName: cloudflare-tls
