# mariadb/secrets/mariadb.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: apps
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: my-secret-store
    kind: ClusterSecretStore
  target:
    name: mariadb
    creationPolicy: Owner
  data:
    - secretKey: mariadb-user
      remoteRef:
        key: mysql_user
    - secretKey: mariadb-password
      remoteRef:
        key: mysql_password
    - secretKey: mariadb-root-password
      remoteRef:
        key: mysql_root_password
    - secretKey: myaac-mariadb-database
      remoteRef:
        key: mysql_database