apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tibia
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tibia-oce/infrastructure
  ref:
    branch: main

