apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nginx

# resources:
# - traefik

# secretGenerator:
#   - name: cloudflare-tls
#     namespace: kube-system
#     files:
#       - tls.crt=public_cert.pem
#       - tls.key=private_key.pem
#     type: "kubernetes.io/tls"

# generatorOptions:
#   disableNameSuffixHash: true
