apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: apps
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.2.1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: PMA_PORT
              value: "3306"
            - name: PMA_HOST
              value: "mariadb.apps.svc.cluster.local"
