apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "secrets", "configmaps", "pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io", "extensions"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["traefik.containo.us"]
  resources: [
    "middlewares", 
    "middlewaretcps", 
    "traefikservices", 
    "ingressroutes", 
    "ingressrouteudps", 
    "ingressroutetcps", 
    "tlsstores", 
    "tlsoptions", 
    "serverstransports"
  ]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
