apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.9
        args:
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--api.dashboard=true"
          - "--api.insecure=true"
          - "--providers.kubernetescrd"
          - "--providers.kubernetesingress"
        ports:
          - name: web
            containerPort: 80
          - name: websecure
            containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/traefik
        - name: kube-ca-cert
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca.crt
      volumes:
      - name: config
        configMap:
          name: traefik-config
      - name: kube-ca-cert
        configMap:
          name: kube-root-ca.crt
