apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik
resources:
  - https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - rolebinding.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - ingressroute.yaml
