apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- rolebinding.yaml
- configmap.yaml
- service.yaml
- deployment.yaml
- ingressroute.yaml

