# kubernetes/traefik/clusterrole.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - secrets
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traefik.io
  - containo.us
  resources:
  - tlsstores
  - ingressroutes
  - ingressroutetcps
  - ingressrouteudps
  - traefikservices
  - middlewares
  - middlewaretcps
  - tlsoptions
  - serverstransports
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - traefik.containo.us
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
