apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  replicas: 1
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v2.5
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080  # Optional: Traefik dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: http  # Add a name for the HTTP port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https  # Add a name for the HTTPS port
      protocol: TCP
      port: 443
      targetPort: 443
    - name: web-dashboard  # Optional: Traefik dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
