name: Renovate

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
            configurationFile: .github/renovate.json5
