name: Renovate

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.RENOVATE_BOT_APP_ID }}"
          private-key: "${{ secrets.RENOVATE_BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.app-token.outputs.token }}"